version: '3.8'
services:
  app:
    container_name: xmlToJson_2
    build: .
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - data:/output
    networks:
      - mongo
volumes:
  'data':
    external:
      name: fs.gsmhp.local/EDI
networks:
  mongo:
    name: mongodb_default
